# This file defines the menus on the website. See the documentation for
# details: http://docs.bolt.cm/menus

main:
  - label: Wie
    path: entry/1
  - label: Wat
    path: page/wat-is-studio-de-paardenstal-flexplek-amsterdam-oost
    title: Studio De Paardenstal is een samenwerkingsvernband van zelfstandige professionals in Amsterdam
  - label: Projecten
    path: page/1
  - label: Wie
    path: page/ontmoet-de-deelnemers
    title: Dit zijn de mensen aan Studio De Paardenstal
  - label: Waar
    path: page/contact-mauritskade-55d-amsterdam
    title: Studio De paardenstal zit op een mooie locatie aan de rand van het Oosterpark
  - label: The Bolt site
    link: http://bolt.cm
    class: last